[package]
name = "nix-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
# default = ["profiling"]
profiling = []

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.89"
quote = "1.0.37"
venial = "0.6.0"
syn = { version = "2.0.98", features = ["full"] }
